### ISSUE TITLE
gpu/xk nodes settings

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#22]
To use OpenMM with GPUs one needs xk nodes, what would be the correct settings inresource_config.rcfg to get xk nodes? Is it simply PILOTSIZE   = 256:xk?

**Comment by vivek-bala** [comment]
Ah using GPUs requires an unreleased version of RP and a different branch of EnTK. There isn't too much documentation currently on it. I'll translate the CPU version into a GPU one. Can you point me to the branch I should work on?

**Comment by euhruska** [comment]
openmm branch

**Comment by vivek-bala** [comment]
Can you give me a timeline of when this would be required? Is it ok if this is available on on the 29th or so?

**Comment by euhruska** [comment]
29th is fine

**Comment by euhruska** [comment]
how does the GPU setup look like?

**Comment by vivek-bala** [comment]
Added the GPU enabled script now. Take a look. I added comments at the beginning of the script to describe the changes. 

Note that you have to use the following branches (the order of installation is important):

radical.utils - devel
saga - feature/gpu
radical.pilot - feature/gpu
radical.entk - feature/gpu

I have changed the installation instructions in the README.

Let me know how it goes.

**Comment by euhruska** [comment]
should I use 'ncsa.bw' or 'ncsa.bw_aprun'?

**Comment by vivek-bala** [comment]
I would start with ncsa.bw_aprun

**Comment by euhruska** [comment]
currently 'ncsa.bw_aprun' gives an error even without gpu, https://github.com/radical-collaboration/extasy-grlsd/issues/44, but I will test once it works again

**Comment by euhruska** [comment]
how do I have to change the resource description?
```
2018-02-02 11:07:54,988: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Failed to validate resource description, error: Error: Mandatory key cpus does not exist in the resource description
Error: Error: Mandatory key cpus does not exist in the resource description
Traceback (most recent call last):
  File "extasy_grlsd.py", line 301, in <module>
    rman = ResourceManager(res_dict)
  File "x/conda/envs/extasy3-gpu/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 48, in __init__
    if self._validate_resource_desc(resource_desc):
  File "x/conda/envs/extasy3-gpu/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 228, in _validate_resource_desc
    raise Error(text='Mandatory key %s does not exist in the resource description'%key)
Error: Error: Mandatory key cpus does not exist in the resource description
```

**Comment by vivek-bala** [comment]
The resource dictionary is different for the gpu branch. See the example at the top of the script: https://github.com/radical-collaboration/extasy-grlsd/blob/feature/gpu/extasy_grlsd2.py#L52-L62. You need to explicitly mention the 'cpus' and 'gpus' to acquire.

**Comment by euhruska** [comment]
ah, missed the branch

**Comment by euhruska** [comment]
Do I understand correctly that he the openmm task be assigned 16 cpus and 1 gpu if I don't set cpu_reqs only sim_task.gpu_reqs = {   'processes': 1,   'process_type': 'MPI',    'threads_per_process': 16,  'thread_type': 'OpenMP'   } ?

**Comment by euhruska** [comment]
how to define mq_connection?
```
2018-02-02 14:38:51,298: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error setting RabbitMQ system: global name 'mq_connection' is not defined
2018-02-02 14:38:51,298: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):                        
  File "/scratch1/eh22/conda/envs/extasy3-gpu/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 225, in run
    setup = self._setup_mqs()                             
  File "/scratch1/eh22/conda/envs/extasy3-gpu/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 557, in _setup_mqs
    self._mq_channel = mq_connection.channel()            
NameError: global name 'mq_connection' is not defined     

```

**Comment by vivek-bala** [comment]
> NameError: global name 'mq_connection' is not defined  

Fixed that. Please pull and reinstall entk.

> Do I understand correctly that he the openmm task be assigned 16 cpus and 1 gpu if I don't set cpu_reqs only sim_task.gpu_reqs = { 'processes': 1, 'process_type': 'MPI', 'threads_per_process': 16, 'thread_type': 'OpenMP' } ?

No. You have to explicitly mention the cpu reqs. 

```
sim_task.gpu_reqs = { 'processes': 1, 'process_type': 'MPI', 'threads_per_process': 16, 'thread_type': 'OpenMP' } 
```

means 16 gpus (processes*threads_per_process) for each sim_task. If you require 16 cpus and 1 gpu for your task, your task description needs to look like ():

```
sim_task.cpu_reqs = { 'processes': 1, 'process_type': None, 'threads_per_process': 16, 'thread_type': 'OpenMP' }  # if the simulation is going to spawn 1 process with 16 threads (i.e. non-mpi)
sim_task.cpu_reqs = { 'processes': 1, 'process_type': None, 'threads_per_process': 16, 'thread_type': 'OpenMP' }  # if the simulation is going to spawn 16 process with 1 threads (i.e. mpi)
sim_task.gpu_reqs = { 'processes': 1, 'process_type': None, 'threads_per_process': 1, 'thread_type': None} 
```

Does that help?

**Comment by euhruska** [comment]
helpful, with openmm I intend to use 1 cpu, 1 gpu

**Comment by euhruska** [comment]
```
2018-02-02 15:09:45,721: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2018-02-02 15:09:45,739: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed 2018-02-02 15:09:45,740: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager                      
Traceback (most recent call last):                                                                                                                        File "/scratch1/eh22/conda/envs/extasy3-gpu/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 242, in run                      
    self._resource_manager._submit_resource_request()                                                                                                     File "/scratch1/eh22/conda/envs/extasy3-gpu/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 368, in _submit_resource_reque
st                                                                                                                                                          raise Exception                                                       
Exception    
```
Looks like error ``` while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory ```
[rp.session.leonardo.rice.edu.eh22.017564.0000.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1690892/rp.session.leonardo.rice.edu.eh22.017564.0000.zip)

**Comment by euhruska** [comment]
is that related to https://github.com/radical-collaboration/extasy-grlsd/issues/44?

**Comment by euhruska** [comment]
used "ncsa.bw_aprun"

**Comment by euhruska** [comment]
it seems the submitted job didn't requested any GPUs, ```qstat``` gives 
```
Resource_List.nodes = 8:ppn=32
```

**Comment by euhruska** [comment]
missing the :xk at the end of the line

**Comment by vivek-bala** [comment]
This is related to https://github.com/radical-cybertools/radical.pilot/issues/1546. I think there are some changes in the python module on BW. It is currently being worked over (https://github.com/radical-cybertools/radical.pilot/pull/1550). I think this issue will be encountered in the gpu and cpu-only versions we have here.

**Comment by euhruska** [comment]
my MD (with gpu) unit starts but doesn't do anything, I tried looking at the logfiles but couldn't pin the problem on anything, can someone look at them?
[rp.session.leonardo.rice.edu.eh22.017576.0001-remote.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1722714/rp.session.leonardo.rice.edu.eh22.017576.0001-remote.zip)

**Comment by andre-merzky** [comment]
Several units finish ok, or so it seems:

```
$ tail -n 1 uni*/*OUT | grep App
Application 65079529 resources: utime ~0s, stime ~1s, Rss ~28408, inblocks ~7297, outblocks ~2289
Application 65079531 resources: utime ~1s, stime ~3s, Rss ~80100, inblocks ~40303, outblocks ~926
Application 65079534 resources: utime ~1s, stime ~3s, Rss ~41180, inblocks ~68272, outblocks ~11
```

But some also report errors:
```
$ tail -n 1 uni*/*ERR
==> unit.000009/STDERR <==
TypeError: an integer is required

==> unit.000010/STDERR <==
IOError: [Errno 2] No such file or directory: 'tmpha.gro'
```

Most importantly though, the application schedules non-mpi units which are larger than a node:
```
$ grep raise *log
agent_0.scheduling.0.child.log:    raise ValueError('Non-mpi unit does not fit onto single node')
agent_0.scheduling.0.child.log:    raise ValueError('Non-mpi unit does not fit onto single node')
agent_0.scheduling.0.child.log:    raise ValueError('Non-mpi unit does not fit onto single node')
agent_0.scheduling.0.child.log:    raise ValueError('Non-mpi unit does not fit onto single node')
agent_0.scheduling.0.child.log:    raise ValueError('Non-mpi unit does not fit onto single node')
agent_0.scheduling.0.child.log:    raise ValueError('Non-mpi unit does not fit onto single node')
agent_0.scheduling.0.child.log:    raise ValueError('Non-mpi unit does not fit onto single node')
agent_0.scheduling.0.child.log:    raise ValueError('Non-mpi unit does not fit onto single node')
```

HtH,  Andre.

**Comment by euhruska** [comment]
Now that #44 is fixed, I have rerun this, the ```raise ValueError('Non-mpi unit does not fit onto single node')``` is the main problem, it happens in units with MD Simulations.
I believe, it can't find fit the gpu requirement, since only xe nodes(no GPUs) instead of xk nodes (with GPUs) are requested. I checked with ```qstat```, gives ``` Resource_List.nodes = 8:ppn=32```. Correctly it should be ``` Resource_List.nodes = 8:ppn=32:xk```
How do I make sure that xk nodes are requested on bluewaters?

**Comment by euhruska** [comment]
@vivek-bala @andre-merzky Can you look at this? It looks like the resources are requested in the wrong queue. Should be gpu ="xk" queue, but currently is only cpu queue.

**Comment by andre-merzky** [comment]
@euhruska : sorry for the delay on this, I'll try to look into it tomorrow.

**Comment by euhruska** [comment]
@vivek-bala @andre-merzky any updates?

**Comment by andre-merzky** [comment]
Hey @euhruska , I finally got around to look at this.  Would you please switch SAGA from `feature/gpu` to `fix/issue_663`, and give it a try?  It should now add `:xk` on BW as soon as any GPUs are requested as part of the pilot description.

**Comment by euhruska** [comment]
it still shows ```Resource_List.nodes = 8:ppn=32``` without :xk
even though the requested resources in the MD stage are:
```
              sim_task.gpu_reqs = { 'processes': 1,
                                    'process_type': None,
                                    'threads_per_process': 1,
                                    'thread_type': None
                                }
              sim_task.cpu_reqs = { 'processes': 1,
                                    'process_type': None,
                                    'threads_per_process': 1,
                                    'thread_type': None
                                  }
```

**Comment by euhruska** [comment]
Reinstalled all radical components, got at first 
```
2018-03-10 20:01:32,236: radical.entk.resource_manager.0000: MainProcess
             : MainThread     : ERROR   : Failed to validate resource descriptio
n, error: Error: Key cores does not exist in the resource description
Error: Error: Key cores does not exist in the resource description
Traceback (most recent call last):
  File "extasy_grlsd.py", line 353, in <module>
    appman.resource_manager = rman
  File "/scratch1/eh22/conda/envs/extasy3-gpu-2/lib/python2.7/site-packages/rad$
cal/entk/appman/appmanager.py", line 158, in resource_manager
    if self._resource_manager._validate_resource_desc(self._sid):
  File "/scratch1/eh22/conda/envs/extasy3-gpu-2/lib/python2.7/site-packages/rad$
cal/entk/execman/resource_manager.py", line 188, in _validate_resource_desc
    raise Error(text='Key %s does not exist in the resource description' % key)
Error: Error: Key cores does not exist in the resource description
```
added cores beside cpus and gpus, now
```
          res_dict = {
            'resource': Kconfig.REMOTE_HOST,
            'walltime': Kconfig.WALLTIME,
            'cores': Kconfig.PILOTSIZE,
            'cpus': Kconfig.PILOTSIZE,
            'gpus': Kconfig.PILOTSIZE/32,
            'project': Kconfig.ALLOCATION,
            'queue': Kconfig.QUEUE,
            'access_schema': 'gsissh'
          }
```
But still qstat -f gives nodes without xk.

**Comment by andre-merzky** [comment]
Thanks Eugene.  I am back on BW now, too.   Let me check.

**Comment by euhruska** [comment]
remote: [rp.session.leonardo.rice.edu.eh22.017601.0004.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1800004/rp.session.leonardo.rice.edu.eh22.017601.0004.zip)

**Comment by andre-merzky** [comment]
Eugene - the following stack (edited) should get the pilots submitted with `:xk` flagged when GPUs are requested:

```
$ rs

  python               : 2.7.14
  pythonpath           : /opt/xalt/0.7.6/sles11.3/libexec
  virtualenv           : /mnt/a/u/sciteam/merzky/radical/radical.pilot/ve

  radical.pilot        : 0.47-0.47-152-g44010335@feature-gpu
  radical.utils        : 0.47.1-v0.47.1-14-gdfd3df5@devel
  saga                 : 0.47-v0.46-71-g207b66e3@fix-issue_663
```
For testing, I used `examples/misc/gpu_pilot.py`, where I set `pd.gpus = 2`.   SAGA was setting `ppn=32`, that is now corrected to `ppn=16`, which seems required for XK nodes.

**Comment by euhruska** [comment]
is the radical.pilot branch feature/gpu?

**Comment by euhruska** [comment]
I can't find or activate /mnt/a/u/sciteam/merzky/radical/radical.pilot/ve.

**Comment by euhruska** [comment]
when installing these branches myself I still get nodes without :xk

**Comment by andre-merzky** [comment]
Yes, that would need the `feature/GPU` stack in RP, as the pilot can otherwise not express the need for GPUs.  Can you send me the output of `radical-stack`, please?  In the test you used, can you please check that the pilot indeed requests GPUs?  If it does, please run again with these settings:

```
export RADICAL_SAGA_VERBOSE=debug
export RADICAL_SAGA_PTY_VERBOSE=debug
export RADICAL_SAGA_LOG_TGT=rs.log
export RADICAL_SAGA_PTY_LOG_TGT=rs.log
```

and attach the resulting `rs.log`, and the script you are running.  Thanks!

**Comment by euhruska** [comment]
radical-stack:
```

  python               : 2.7.14
  pythonpath           :
  virtualenv           : extasy3-gpu-3

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.entk         : 0.6.1-entk-0.5-306-ga1887fc@HEAD-detached-at-a1887fc
  radical.pilot        : 0.47-0.47-118-gf66e2f6d@feature-gpu
  radical.utils        : 0.47.1-v0.47.1-14-gdfd3df5@devel
  saga                 : 0.47-v0.46-71-g207b66e3@HEAD-detached-at-207b66e3
```
I does not request gpus, at least the qstat -f does not show that

**Comment by euhruska** [comment]
the script I'm running is https://github.com/radical-collaboration/extasy-grlsd/blob/master/extasy_grlsd.py with ```python extasy_grlsd.py --Kconfig settings_ala12-gpu.wcfg```

**Comment by andre-merzky** [comment]
@vivek-bala : Vivek, I don't see a GPU mentioned in that settings file.  Can you confirm if or if not the pilot will request GPUs in this case?
@euhruska : can you please attach either the SAGA logs, or `pmgr.0000.launching.0.child.log` from the RP session directory?  Thanks!

**Comment by vivek-bala** [comment]
Hey Eugen, it seems like you are using the latest master of EnTK. You have to use the latest feature/gpu branch in EnTK.

**Comment by vivek-bala** [comment]
Hey Andre, yes I do see the use_gpus variable in the config file. I think it was a mismatch on the branches. IIUC: Eugen needs to use (always) feature/gpu branch in EnTK, RP and Saga and devel of utils.

**Comment by andre-merzky** [comment]
`settings_ala12-gpu.wcfg` does not exist in the GPU branch though.  Can you help Eugene to make sure he uses a suitable config file to trigger the GPU allocation request?  Thanks!

**Comment by euhruska** [comment]
I'm not using the gpu branch of extasy-grlsd, updating the master

**Comment by euhruska** [comment]
ok, will reinstall EnTK, RP and saga

**Comment by vivek-bala** [comment]
Oh yea, I was looking at master since the script linked above is from master. Eugen, try the stack I mentioned with the gpu-compatible branch/files in extasy-grlsd. Let us know how it goes.

**Comment by euhruska** [comment]
In the mean time rs.log and pmgr.0000.launching.0.child.log before with the last radical-stack
[pmgr.0000.launching.0.child.log](https://github.com/radical-collaboration/extasy-grlsd/files/1813407/pmgr.0000.launching.0.child.log)
[rs.log](https://github.com/radical-collaboration/extasy-grlsd/files/1813408/rs.log)

**Comment by euhruska** [comment]
but got radical-stack with some HEAD detached, is that correct
```
radical-stack

  python               : 2.7.14
  pythonpath           :
  virtualenv           : extasy3-gpu-3

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.entk         : 0.6.1-entk-0.5-310-g301af1d@HEAD-detached-at-301af1d
  radical.pilot        : 0.47-0.47-152-g44010335@HEAD-detached-at-44010335
  radical.utils        : 0.47.1-v0.47.1-14-gdfd3df5@devel
  saga                 : 0.47-v0.46-70-g23bd68a3@HEAD-detached-at-23bd68a3
```
I used:
```
pip install git+https://github.com/radical-cybertools/radical.utils.git@devel
pip install git+https://github.com/radical-cybertools/saga-python.git@feature/gpu
pip install git+https://github.com/radical-cybertools/radical.pilot.git@feature/gpu
pip install git+https://github.com/radical-cybertools/radical.entk.git@feature/gpu
pip install git+https://github.com/radical-cybertools/radical.analytics@devel
```

**Comment by euhruska** [comment]
the above stack gives still no :xk nodes, are the above commands correct?

**Comment by andre-merzky** [comment]
That stack looks almost great - but per [this comment](https://github.com/radical-collaboration/extasy-grlsd/issues/22#issuecomment-372090362) you will need to use `0.47-v0.46-71-g207b66e3@fix-issue_663`.  I assume this would be 
```
pip install git+https://github.com/radical-cybertools/saga-python.git@fix/issue_663
```
(I usually don't use pip this way, so I am not sure, but you get the gist).

**Comment by euhruska** [comment]
I thin there is a difference between using ```pip install git+https://github.com/radical-cybertools/radical.entk.git@feature/gpu``` and checking out a branch and pip install., now have radical-stack:
```

  python               : 2.7.14
  pythonpath           :
  virtualenv           : extasy3-gpu-3

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.entk         : 0.6.1-entk-0.5-310-g301af1d@feature-gpu
  radical.pilot        : 0.47-0.47-152-g44010335@feature-gpu
  radical.utils        : 0.47.1-v0.47.1-15-g073c892@devel
  saga                 : 0.47-v0.46-72-gc86187fb@fix-issue_663
```

**Comment by euhruska** [comment]
good, qstat-f shows xk nodes

**Comment by euhruska** [comment]
but doesn't seem to run anything
[rp.session.leonardo.rice.edu.eh22.017604.0006.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1813553/rp.session.leonardo.rice.edu.eh22.017604.0006.zip)
[rs.log](https://github.com/radical-collaboration/extasy-grlsd/files/1813554/rs.log)

**Comment by andre-merzky** [comment]
Hmm, the RP logs show not trace of any units being submitted.  @vivek-bala , can you help clarifying whats up, please?

**Comment by vivek-bala** [comment]
You're right, I don't see any units submitted. Eugen, can you run it with RADICAL_ENTK_VERBOSE=DEBUG and point me to the script that you are running please. I am not sure whether you are using master or the gpu branch of extasy-grlsd.

**Comment by euhruska** [comment]
the current script is at the master branch: https://github.com/radical-collaboration/extasy-grlsd/blob/master/extasy_grlsd.py 
command ```python extasy_grlsd.py --Kconfig settings_ala12-gpu.wcfg```

**Comment by euhruska** [comment]
session with  RADICAL_ENTK_VERBOSE=DEBUG, not there are some units, non-MD unit ran, but the MD (GPU) units don't run
[re.session.leonardo.rice.edu.eh22.017605.0002.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1817226/re.session.leonardo.rice.edu.eh22.017605.0002.zip)
[rs.log](https://github.com/radical-collaboration/extasy-grlsd/files/1817227/rs.log)
[rp.session.leonardo.rice.edu.eh22.017605.0003.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1817228/rp.session.leonardo.rice.edu.eh22.017605.0003.zip)

**Comment by vivek-bala** [comment]
Thanks Eugen, can you run 
```
radicalpilot-fetch-logfiles rp.session.leonardo.rice.edu.eh22.017605.0003
```
 from the location where you have the rp.session.leonardo.rice.edu.eh22.017605.0003 folder. That should fetch the log files from the agent side as well (with the filename format agent.*.log). Please reupload rp.session.leonardo.rice.edu.eh22.017605.0003.zip.

I'll take a look at the logs later in the evening and keep you posted. The grlsd script looks fine as it is.

**Comment by euhruska** [comment]
[rp.session.leonardo.rice.edu.eh22.017605.0003.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1817258/rp.session.leonardo.rice.edu.eh22.017605.0003.zip)

**Comment by andre-merzky** [comment]
Thanks for your patience, Eugene - but the pilot side log files don't seem to be included yet.  Can you please pack them, too?  Thanks!

**Comment by euhruska** [comment]
is this correct?
[rp.session.leonardo.rice.edu.eh22.017605.0003.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1817360/rp.session.leonardo.rice.edu.eh22.017605.0003.zip)

**Comment by andre-merzky** [comment]
Thanks, those help!

What happens is that 16 GPUs are requested - but the agent scsheduler sees `gpus_per_node` set to zero, and thus does not manage to place those CUs which actually need a GPU.  I need to dig where that setting comes from...

**Comment by andre-merzky** [comment]
Yeah, there goes something wrong with the resource inspection in the agent.  For now, I hardcoded the number of GPUs in the NCSA config file.  Eugene, can you please update the `feature/gpu` branch in radical.pilot, and try again?

**Comment by euhruska** [comment]
seems like this time no units
[rp.session.leonardo.rice.edu.eh22.017605.0005.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1817427/rp.session.leonardo.rice.edu.eh22.017605.0005.zip)
[re.session.leonardo.rice.edu.eh22.017605.0004.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1817428/re.session.leonardo.rice.edu.eh22.017605.0004.zip)
[rs.log](https://github.com/radical-collaboration/extasy-grlsd/files/1817429/rs.log)

**Comment by andre-merzky** [comment]
yeah, no units are submitted indeed.  @vivek-bala: can you help?

**Comment by vivek-bala** [comment]
Huh.. one of the EnTK processes doesn't even start. Let me see what's happening. I'll recreate the stack and run the grlsd.py script from master. I am assuming the required data is there as well. Thanks for your patience on this Eugen!

**Comment by vivek-bala** [comment]
The bootstrapper fails for me. Possibly something switched on BW? Bootstrapper output attached,

I have the following stack:
```
$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/vivek/ves/ve-extasy

  radical.entk         : 0.6.1-entk-0.5-310-g301af1d@feature-gpu
  radical.pilot        : 0.47-0.47-154-g98884456@feature-gpu
  radical.utils        : 0.47.1-v0.47.1-15-g073c892@devel
  saga                 : 0.47-v0.46-72-gc86187fb@fix-issue_663
```


[bootstrap_1.txt](https://github.com/radical-collaboration/extasy-grlsd/files/1820800/bootstrap_1.txt)

**Comment by euhruska** [comment]
my radical-stack is the same:
```

  python               : 2.7.14
  pythonpath           :
  virtualenv           : extasy3-gpu-3

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.entk         : 0.6.1-entk-0.5-310-g301af1d@feature-gpu
  radical.pilot        : 0.47-0.47-154-g98884456@feature-gpu
  radical.utils        : 0.47.1-v0.47.1-15-g073c892@devel
  saga                 : 0.47-v0.46-72-gc86187fb@fix-issue_663
```

**Comment by vivek-bala** [comment]
Yea, I tried to match it. I am hoping BW didn't change anything overnight. Let's see what Andre says from the bootstrap log.

**Comment by andre-merzky** [comment]
This looks like a change in the Python module, again...  Grrr...

**Comment by euhruska** [comment]
is there a way to make our own python module, so the bw python changes don't affect extasy?

**Comment by andre-merzky** [comment]
No,  that is too much effort,  unfortunately.

**Comment by euhruska** [comment]
are there some instructions how I could adjust the latest change in the python module?  If not, can you please adjust it?

**Comment by andre-merzky** [comment]
The specific of this ticket problem should be addressed with radical-cybertools/radical.pilot/pull/1550 I think, at least in the context of radical-cybertools/radical.pilot/issues/1546.  Vivek's problem reported above related to the same error (Sorry, I should have reported that this was resolved in this ticket).

But maybe I misunderstand the question - can you elaborate what you are looking for?

**Comment by euhruska** [comment]
ah, didn't see it;s resolved

**Comment by andre-merzky** [comment]
Ah, great - no worries then, sorry for the lack of update.  We will require the manual creation of the agent VE for a while though...

**Comment by euhruska** [comment]
the bootstrap has no errors, but no units generated

[re.session.leonardo.rice.edu.eh22.017610.0004.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1835352/re.session.leonardo.rice.edu.eh22.017610.0004.zip)
[rp.session.leonardo.rice.edu.eh22.017610.0005.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1835353/rp.session.leonardo.rice.edu.eh22.017610.0005.zip)
[rs.log](https://github.com/radical-collaboration/extasy-grlsd/files/1835354/rs.log)

**Comment by vivek-bala** [comment]
I recreated the ve as well. Testing the unit submissions.

**Comment by vivek-bala** [comment]
Hey Eugen, I tried again starting with a fresh virtualenv and rabbitmq instance. The units seemed to be
submitted and the simulation tasks are currently running. Could you also try a fresh virtualenv+rabbitmq?

Feel free to use the docker instance of RabbitMQ i am using. You can use it by setting in AppManager the following:
```
AppManager(hostname='two.radical-project.org', port=33118)
```

**Comment by euhruska** [comment]
Made a fresh virtualenv, rabbitmq, still no units.
But with your RabbitMQ there are units and MD runs on GPU nodes. Any idea what is the difference?

**Comment by vivek-bala** [comment]
You mean it works with the RabbitMQ I have but not with yours? In that case, can you try restarting your rabbitmq server (maybe it got left in an inconsistet state during termination, there is also known issue of rabbitmq becoming unresponsive for long running tasks - this can be fixed by upgrading to the latest rabbitmq release).

**Comment by euhruska** [comment]
I usually make shut it down and start fresh at beginning of a run. Was a fresh installation  3.7.4

**Comment by vivek-bala** [comment]
Hmmm, that's a new one. Can you send me the RabbitMQ logs of that server? (https://www.rabbitmq.com/relocate.html) or ```docker logs <container name``` if you are running it under docker.

**Comment by euhruska** [comment]
I don't use docker, here the log file
[rabbit@leonardo.log](https://github.com/radical-collaboration/extasy-grlsd/files/1845876/rabbit.leonardo.log)

**Comment by euhruska** [comment]
it seems it only runs 7 units, finishes them and then doesn't start any new

**Comment by vivek-bala** [comment]
Can you attach the agent+client side sandbox please? In my run, the execution reaches the post analysis task, but that task runs for more 100mins and we hit the walltime (120 mins).

Sandboxes attached.
[bw-sandbox.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1846004/bw-sandbox.zip)

**Comment by euhruska** [comment]
the sandboxes have too many files in it, do you need more directories? I couldn't get radicalpilot-fetch-logfiles to run
[rp.session.leonardo.rice.edu.eh22.017615.0005.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1849099/rp.session.leonardo.rice.edu.eh22.017615.0005.zip)
[rp.session.leonardo.rice.edu.eh22.017615.0005-remote.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1849100/rp.session.leonardo.rice.edu.eh22.017615.0005-remote.zip)
[re.session.leonardo.rice.edu.eh22.017615.0004.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1849101/re.session.leonardo.rice.edu.eh22.017615.0004.zip)

**Comment by euhruska** [comment]
any idea how to fix this?

**Comment by andre-merzky** [comment]
@euhruska , @vivek-bala : I assume I cannot contribute on the ticket right now, as this is now in EnTK land.  But please ping me if you think otherwise!

**Comment by vivek-bala** [comment]
Hey Eugen,  do you always get 7 units running only? For me, it seems like it waits in the post-analysis stage and waits for the task to finish. The task is long enough to run past the walltime. I'll look at the logs.

FYI I am seeing new RP failures on BW (https://github.com/radical-cybertools/radical.pilot/issues/1591), possibly related to yet another change in the python distribution.

**Comment by andre-merzky** [comment]
@vivek-bala, @euhruska: can we close the RP ticket, and move this discussion over to EnTK?

**Comment by euhruska** [comment]
As an extasy-grlsd issue I would like to keep this issue open. If there is a way to label it EnTK, that's fine by me. On Mar 31, 2018 03:14, Andre Merzky <notifications@github.com> wrote:@vivek-bala, @euhruska: can we close the RP ticket, and move this discussion over to EnTK?

**Comment by andre-merzky** [comment]
Ah, my wrong - this is not an RP issue! :-)
Apologies, Andre.

**Comment by euhruska** [comment]
yeah, updated and still getting 7 units. The wierd part is that the 7th unit (MD) finishes, but the next one  does not even start. The next one should be still MD, since the extasy_grld.py creates 8 (num_parallel_MD_sim) MD units, see https://github.com/radical-collaboration/extasy-grlsd/blob/master/extasy_grlsd.py#L86. Only after that, an pre-analysis unit comes, which is quite fast. This is not caused by the 120 min limit.

**Comment by euhruska** [comment]
Is the command radicalpilot-fetch-logfiles still correct, I get a ```command not found```
 My current radical-stack

  python               : 2.7.14
  pythonpath           :
  virtualenv           : extasy5

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.entk         : 0.6.1-entk-0.5-310-g301af1d@feature-gpu
  radical.pilot        : 0.47-0.47-154-g98884456@feature-gpu
  radical.utils        : 0.47.3-v0.47.3@devel
  saga                 : 0.47-v0.46-72-gc86187fb@fix-issue_663

My current session zips:
[rp.session.leonardo.rice.edu.eh22.017623.0001.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1869472/rp.session.leonardo.rice.edu.eh22.017623.0001.zip)
[re.session.leonardo.rice.edu.eh22.017623.0000.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1869473/re.session.leonardo.rice.edu.eh22.017623.0000.zip)

**Comment by andre-merzky** [comment]
With the latest release, we have renamed some of the tools to make the names consistent, from `radicalpilot-*` to `radical-pilot-*`.

**Comment by euhruska** [comment]
Ah, found the new command
It seems that only 7 units are run independent how many MD units there are. I have set the number of MD units to 4, they ran normally, also the pre, analysis and post-analysis units ran properly. The post-analysis it got an error ```aprun: Apid 65961825: Caught signal Terminated, sending to application```. I can't see why it got terminated.
The whole MD unit took about 5 min, so there is no reason it ran out out jobtime-120min.
The pre-analysis and analysis tasks did not get any error, but the MD tasks got ```[NID 20551] 2018-04-02 17:01:31 Apid 65961693: initiated application termination```.
Not sure why after 7 units it stopped just like before, but I can say the problem is not in the pre-analysis unit.
Details
[re.session.leonardo.rice.edu.eh22.017623.0002.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1870070/re.session.leonardo.rice.edu.eh22.017623.0002.zip)
[rp.session.leonardo.rice.edu.eh22.017623.0003.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1870071/rp.session.leonardo.rice.edu.eh22.017623.0003.zip)

**Comment by euhruska** [comment]
Changed to port 33134, but I get no units. @vivek-bala 
[re.session.leonardo.rice.edu.eh22.017626.0000.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1878611/re.session.leonardo.rice.edu.eh22.017626.0000.zip)
[rp.session.leonardo.rice.edu.eh22.017626.0001.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1878612/rp.session.leonardo.rice.edu.eh22.017626.0001.zip)

**Comment by euhruska** [comment]
fixed
